### ISSUE TITLE
为什么登陆的时候总是显示密码错误，我看那个数据库里账号密码都是admin还是报错是为什么

### ISSUE THREAD

**Issue by sky-y11** [srx-2000/transaction#4]
老哥，求解

**Comment by srx-2000** [comment]
嗯？你是否接入了前端呀，如果没有接入前端使用postman之类的接口测试工具的话，检查一下你传入的参数格式，请求头是否正确。如果都没问题的话你可以从以下两个地方打上断点检查一下：
1. https://github.com/srx-2000/transaction/blob/6ff63125e5b185ec6fc0503372eb7098ade630fb/backend/src/main/java/com/srx/transaction/Serivce/Impl/UserServiceImplement.java#L26-L31
这里着重检查一下传入的password是否满足上述if判断条件，如果满足并进入了mapper层，那么就接着看一下下面这段代码
2. https://github.com/srx-2000/transaction/blob/6ff63125e5b185ec6fc0503372eb7098ade630fb/backend/src/main/resources/Mapper/UserMapper.xml#L32-L35
这里着重检查一下传入的username，password是否为数据库中存在的数据，如果存在，那么检查一下status属性是否正确，如果上述检查都没问题，可以看一下其返回是啥在进行进一步的判断。

**Comment by srx-2000** [comment]
这里追加一个检查点：因为当时在写的时候所有的密码都是被md5加密过的，所以在直接向数据库插入用户信息时记得把密码用md5加密一下再存入
